CUDA_VISIBLE_DEVICES=0 python demo.py \
--center-num 48 \
--norm-space \
--adaptive-patch \
--embed-dim 256 \
--patch-size 64 \
--anchor-w 60 \
--grid-size 12 \
--all-points-num 25600 \
--group-num 512 \
--local-k 10 \
--ratio 8 \
--anchor-num 7 \
--anchor-k 6 \
--anchor-z 20 \
--input-h 360 \
--input-w 640 \
--local-thres 0.01 \
--heatmap-thres 0.01 \
--checkpoint './checkpoints/realsense' \
--rgb-path './images/demo_rgb.png' \
--depth-path './images/demo_depth.png'
